LIBMOBILE-1277- fix androidx lifecycle causes analytics init in background crash
segmentio/analytics-kotlin pull request #158
Opened 2023-04-28 05:34 UTC by RawatRaveena

LIBMOBILE-1277
- fix androidx lifecycle causes analytics init in background crash

2023-04-28 16:45 UTC, wenxi-zeng requested changes

2023-04-28 16:45 UTC, wenxi-zeng commented on android/src/main/java/com/segment/analytics/kotlin/android/plugins/AndroidLifecyclePlugin.kt
> +    private fun run(runnable: Runnable) {
you don't have to use runnable in kotlin, try [high order function and lambda](https://kotlinlang.org/docs/lambdas.html)

2023-04-28 16:45 UTC, wenxi-zeng commented on android/src/main/java/com/segment/analytics/kotlin/android/plugins/AndroidLifecyclePlugin.kt
> +            HANDLER.post(runnable)
in kotlin, the correct way to post to main thread is 
```
launch(Dispatchers.Main) {
  // do something on main thread
}
```

2023-05-09 17:55 UTC, didiergarcia approved these changes

2023-05-09 19:50 UTC, wenxi-zeng approved these changes

2023-05-09 19:51 UTC, merged